### PR TITLE
Fix JS, which was already fixed in stable core, but not in this XLASS…

### PR DESCRIPTION
**Pull request by weber-ebusiness**
…. The Problem is that the sorting in list module don't work. Maybe there are other left changes?!.

### CODE REVIEW

**Comment by mgrundkoetter** [comment]
+1, please merge. This is very annoying, as sorting items in list view does not work without this fix. I can confirm that the changes fix the problem in 7.3.1

**Comment by PowerKiKi** [comment]
Unfortunately this is only a mirror, and you won't have much luck with a pull request here.  

You should be able to submit a change [through Gerritt](https://review.typo3.org/#/admin/projects/TYPO3CMS/Extensions/gridelements,branches), though.  I don't know if it's obvious, but anyone who wants to can sign up for a TYPO3 account (via http://typo3.org), which will enable you to submit patches and changes via Gerritt.  It's definitely not as straightforward (:sweat:), nor as pleasant, as submitting a Github pull request, but there's a [Contribution Walkthrough](http://wiki.typo3.org/Contribution_Walkthrough_with_CommandLine) out there.

Sorry about that.

**Comment by mgrundkoetter** [comment]
Yeah, why not forcing people to use CVS to contribute to TYPO3 ;-) Would increase the community dying speed I guess. But anyway: you are not tied to the we-have-our-own-solution-for-everything-policy of the core community as this is just an extension. So why are you using it in favor of also free and much better (read: easier) alternatives like GitHub? @Bunnyfield

**Comment by PowerKiKi** [comment]
I couldn't agree more with you. I feel Gerrit may be a great tool to control "big" open-source project, such as TYPO3 Core. Its "democratic" approach prevent possible issues that could arise if leader(s) disagree... but for extensions, where the project scope is much smaller, I think Gerrit is a PITA. I guess the moderate migrations of extensions from TYPO3 forge/git to GitHub is indeed telling.

To be clear, I have nothing to do with this extension, I just happen to have access right on this GitHub repository.

**Comment by Bunnyfield** [comment]
Well - frankly said: Because it is NOT much better and easier for developers within the TYPO3 project. We have a defined workflow that includes reviews, version tracking and everything else, all tied to a central communication platform on slack. So I can easily track my extensions AND the core without having to deal with pull requests and other stuff happening on widespread channels as i.e. Github.

Please go to http://forger.typo3.org/slack to register
or to https://typo3.slack.com/messages/gridelements/ for the Gridelements channel
and follow the mentioned Contribution Walkthrough, if you want me or other team members to review your changes.

Usually there is somebody around who will answer requests within 24 hours and reaction time regarding bugs and fixes is quite fast, as long as you stick to our defined workflows, which is the only thing we request from you, while the rest is for free. :-)

**Comment by PowerKiKi** [comment]
To each their own :-)

If you don't mind me asking though, why is this mirror here ? It's the third Pull Request that got "confused". Maybe you should consider destroying this mirror ? or at least put a very clear description of where we should contact the team ?

**Comment by Bunnyfield** [comment]
The mirror has been created automatically since people requested TYPO3 extensions to be available on Github as well. Don't know why they did and how they expected the workflow to be combined with the original repositories, but it's just there now, without anyone of the team having asked for it.

You can easily fork stuff this way and try to do your own things though, so still there might be some usecase for Github, but as you already mentioned: This is just a one way mirror, like with any other extension in https://github.com/TYPO3-extensions

**Comment by mgrundkoetter** [comment]
@Bunnyfield Slack is designed to handle multiple input channels, where all other code contribution platforms happen to be supported right out of the box already, so I guess that's not really counting :-) On the other hand, the TYPO3 core community is obviously not valuing contributions made by people outside that inner circle. You said it yourself: "...it is NOT much better and easier for developers within the TYPO3 project.". While this might be true, have you thought about whether it's easier for the rest of the developers wanting to help and to contribute? Developers not "within the TYPO3 project". Even the fact that this community divides the world in this type of groups "within/not within" is a very bad sign, don't you think?

You can count the various contributions made to all the extension mirrors here on GitHub that have already been ignored/deleted or will be in future. It's a lot of love and code that has been written for the dustbin. Instead of finding a **SIMPLE** solution for all those people (e.g. GitHub, BitBucket, whatever), everyone is advised to fork their own stuff. There are more than 6.500 extensions in TER right now and if everyone makes their own forks, this (theoretical) number will grow significantly. Those forks will not be found by anyone else, as they will never find their way into the TER. So the second guy with the same ideas will have to create another fork and so on.

I can only agree with @PowerKiKi and hope that more and more extension developers will move to other platforms in the future, otherwise the mess in TER will increase. Less than 530 extensions in TER got updated during the last 6 months, that is as low as about 8%! I guess with another, more developer and contributor friendly platform, this value would be a lot over 50% and the number of extensions could be about 1.000 or less if more people were involved in the extension review.

**Comment by StephenKing** [comment]
Hello my friends,

please keep calm. We're about to throw all extensions out of the TYPO3 infrastructure, as we absolutely lack the man power to manage it in such a way that you can have a user experience like on the other public platforms.

Please focus on the goal.. make gridelements better. Thanks

Steffen

**Comment by Bunnyfield** [comment]
+1 ;-)

**Comment by PowerKiKi** [comment]
@StephenKing would you have a link talking about this throwing out of extensions ? I am interested in the why's and the how's about that. Maybe some chat on slack ?

**Comment by StephenKing** [comment]
No details, yet. Only a brief discussion at T3DD that server team and TYPO3 CMS team share the same idea. Will try to get things rolling..

**Pull request closed without merging**
