### PR TITLE
Taras dev

### PR DESCRIPTION
**Pull request by taras-pixelant**
Hi)
I'm BE developer from Pixelant. We found bug related to gridelements, it has problem with translation/localization. Especially with actions translate->copy and translate->translate (when you want to translate from language with uid > 1).

screenshot 33

So I made fix for this problem.

### CODE REVIEW

**Comment by jozefspisiak** [comment]
Hey @Bunnyfield , do you have any feedback on this issue? What can we do to help to resolve this?

**Comment by Bunnyfield** [comment]
Hi Jozef.

Since this is a one way mirror of the official TYPO3 git, I don't look into issues mentioned here on a regular base. So you should use the issue tracker on forge.typo3.org instead if you want to make sure things get recognized ;-)

The problem described here is a Core bug of the "Copy" mode, since the "Translation" with another source language than "Default" will use the same behaviour as the "Copy" mode.

When using that mode, elements and possible subelements are just copied and then the top parent element gets another language, while the whole tree of subelements is ignored.

This is true for any other connection to tables like sys_file_reference as well, so this is not a Gridelements problem and will not be solved from the Gridelements side.

But there is a pending core patch you could test, comment on or extend:

https://review.typo3.org/#/c/47645/

**Comment by jozefspisiak** [comment]
Great. Thank you for reply, I will check it on the review server, can you close this pull request? (Taras will probably not close it, since he is not working with us anymore)

**Comment by Bunnyfield** [comment]
Seems that I can not close pull requests

**Pull request closed without merging**
